---
name: CI

on:
  push:

jobs:
  # linter:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0

  #     - name: Lint Code Base
  #       uses: github/super-linter@v3
  #       env:
  #         VALIDATE_ALL_CODEBASE: false
  #         DEFAULT_BRANCH: main
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: |
              pip install -r requirements.txt  
              bandit app.py
              python -m pytest

  build:
    name: Build docker image
    runs-on: ubuntu-latest
    needs:
      - tests
    steps:
      - uses: actions/checkout@v2

      - name: Build and push docker image
        run: | 
          echo $PAT | docker login ghcr.io -u cyriltavian --password-stdin
          docker build --build-arg APP_VERSION="$APP_VERSION" -t $CONTAINER_COMMIT_IMAGE -t $CONTAINER_LATEST_IMAGE .
          docker push $CONTAINER_COMMIT_IMAGE
          docker push $CONTAINER_LATEST_IMAGE
        env:
          PAT: ${{ secrets.DOCKER_TOKEN }}
          APP_VERSION: ${{ github.sha }}
          CONTAINER_REGISTRY: ghcr.io/cyriltavian/github-actions-dojo
          CONTAINER_COMMIT_IMAGE: ghcr.io/ctavian/github-actions-dojo:${{ github.sha }}
          CONTAINER_LATEST_IMAGE: ghcr.io/ctavian/github-actions-dojo:latest