---
name: CI

on:
  push:

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  # tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/setup-python@v2
  #       with:
  #         python-version: '3.6'
      